### ISSUE TITLE
Regarding the issue of 'GIT HASH HEAD' 

### ISSUE THREAD

**Issue by Pinocchio-Jia** [wengflow/robust-e-nerf#2]
I would like to know the impact of obtaining the 'git HASH head' parameter in the code on the subsequent code execution. Since my device is unable to retrieve this parameter, I commented it out and successfully ran the code. I'm wondering if this could lead to different results?

**Comment by wengflow** [comment]
The [lines of code](https://github.com/wengflow/robust-e-nerf/blob/main/scripts/run.py#L27-L29) are used to extract the hash of the commit currently pointed to by the git HEAD, which will be later logged. It is merely used to keep track the code version for each experiment run, hence will not affect the results.

Reference: https://stackoverflow.com/questions/949314/how-do-i-get-the-hash-for-the-current-commit-in-git
